version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.0-node-browsers
    working_directory: ~/hello
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: composer test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
